name: Run rspec tests

on:
  push:
    branches: [ main ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        
    - name: Install rspec
      run: gem install rspec --no-document 
  
    - name: list gems
      run: gem list 

    - name: Run tests chapter 01 - 01
      if: ${{ always() }}
      run: |
        cd chapter_01/01
        rspec
    
    - name: Run tests chapter 01 - 03
      if: ${{ always() }}
      run: |
        cd chapter_01/03
        rspec
    
    - name: Run tests chapter 01 - 04
      if: ${{ always() }}
      run: |
        cd chapter_01/04
        rspec
    
    - name: Run tests chapter 01 - 05
      if: ${{ always() }}
      run: |
        cd chapter_01/05
        rspec
    
    - name: Run tests chapter 01 - 06
      if: ${{ always() }}
      run: |
        cd chapter_01/06
        rspec
    
    - name: Run tests chapter 01 - 07
      if: ${{ always() }}
      run: |
        cd chapter_01/07
        rspec
    
    - name: Run tests chapter 01 - 09
      if: ${{ always() }}
      run: |
        cd chapter_01/09
        rspec
    
    - name: Run tests chapter 02 - 01
      if: ${{ always() }}
      run: |
        cd chapter_02/01
        rspec -f doc
        # run just the examples (-e) that include the term 'milk'
        rspec -f d -e milk
        # run the specifis example on a given line number
        rspec ./spec/coffee_spec.rb:24
    
    - name: Run tests chapter 02 - 03
      if: ${{ always() }}
      run: |
        cd chapter_02/03
        # runs tests and lists the 2 slowest examples
        rspec --profile 2
    
    - name: Run tests chapter 02 - 06
      if: ${{ always() }}
      run: |
        cd chapter_02/06
        rspec -f d
    
    - name: Run tests chapter 02 - 07
      if: ${{ always() }}
      run: |
        cd chapter_02/07
        rspec -f d
    
    - name: Run tests chapter 02 - 08
      if: ${{ always() }}
      run: |
        cd chapter_02/08
        rspec -f d
    
    - name: Run tests chapter 02 - 09
      if: ${{ always() }}
      run: |
        cd chapter_02/09
        rspec -f d
    
    - name: Run tests chapter 02 - 10
      if: ${{ always() }}
      run: |
        cd chapter_02/10
        rspec -f d
    
    - name: Run tests chapter 02 - 11
      if: ${{ always() }}
      run: |
        cd chapter_02/11
        rspec -f d
    
    - name: Run tests chapter 02 - exercises
      if: ${{ always() }}
      run: |
        cd chapter_02/exercises
        rspec -f d -f h -o report.html
    
    - name: Run tests chapter 04 - 01
      if: ${{ always() }}
      run: |
        cd chapter_04/01/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 04 - 02
      if: ${{ always() }}
      run: |
        cd chapter_04/02/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 04 - 03
      if: ${{ always() }}
      run: |
        cd chapter_04/03/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 04 - 04
      if: ${{ always() }}
      run: |
        cd chapter_04/04/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 04 - 05
      if: ${{ always() }}
      run: |
        cd chapter_04/05/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 04 - 06
      if: ${{ always() }}
      run: |
        cd chapter_04/06/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 05 - 01
      if: ${{ always() }}
      run: |
        cd chapter_05/01/expense_tracker
        bundle install
        bundle exec rspec -f d
    
    - name: Run tests chapter 05 - 02
      if: ${{ always() }}
      run: |
        cd chapter_05/02/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 03
      if: ${{ always() }}
      run: |
        cd chapter_05/03/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 04
      if: ${{ always() }}
      run: |
        cd chapter_05/04/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 05
      if: ${{ always() }}
      run: |
        cd chapter_05/05/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 06
      if: ${{ always() }}
      run: |
        cd chapter_05/06/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 07
      if: ${{ always() }}
      run: |
        cd chapter_05/07/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 08
      if: ${{ always() }}
      run: |
        cd chapter_05/08/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 09
      if: ${{ always() }}
      run: |
        cd chapter_05/09/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - 10
      if: ${{ always() }}
      run: |
        cd chapter_05/10/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 05 - exercises
      if: ${{ always() }}
      run: |
        cd chapter_05/exercises/expense_tracker
        bundle install
        bundle exec rspec -f d spec/unit/app/api_spec.rb
    
    - name: Run tests chapter 06 - 03
      if: ${{ always() }}
      run: |
        cd chapter_06/03/expense_tracker
        bundle install
        bundle exec sequel -m ./db/migrations sqlite://db/development.db --echo
        bundle exec rspec -f d spec/integration/app/ledger_spec.rb
    
    - name: Run tests chapter 06 - 04
      if: ${{ always() }}
      run: |
        cd chapter_06/04/expense_tracker
        bundle install
        bundle exec sequel -m ./db/migrations sqlite://db/development.db --echo
        bundle exec rspec -f d spec/integration/app/ledger_spec.rb
    
    - name: Run tests chapter 06 - 05
      if: ${{ always() }}
      run: |
        cd chapter_06/05/expense_tracker
        bundle install
        bundle exec sequel -m ./db/migrations sqlite://db/development.db --echo
        bundle exec rspec -f d spec/integration/app/ledger_spec.rb


