name: Run rspec tests

on:
  push:
    branches: [ main ]

jobs:
  rspec_install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - continue-on-error: true
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        
    - name: Install rspec
      run: gem install rspec --no-document 
  
  rspec_chapter_01:
    - needs: rspec_install

    steps:

    - continue-on-error: true

    - name: Run tests chapter 01 - 01
      run: |
        cd chapter_01/01
        rspec
    
    - name: Run tests chapter 01 - 03
      run: |
        cd ../03
        rspec
    
    - name: Run tests chapter 01 - 04
      run: |
        cd ../04
        rspec
    
    - name: Run tests chapter 01 - 05
      run: |
        cd ../05
        rspec
    
    - name: Run tests chapter 01 - 06
      run: |
        cd ../06
        rspec
    
    - name: Run tests chapter 01 - 07
      run: |
        cd ../07
        rspec
    
    - name: Run tests chapter 01 - 09
      run: |
        cd ../09
        rspec
