name: Run rspec tests

on:
  push:
    branches: [ main ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    continue-on-error: true
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        
    - name: Install rspec
      run: gem install rspec --no-document 
  
