name: Run rspec tests

on:
  push:
    branches: [ main ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        
    - name: Install rspec
      run: gem install rspec --no-document 
  
    - name: list gems
      run: gem list 

    - name: Run tests chapter 01 - 01
      run: |
        continue-on-error: true
        cd chapter_01/01
        rspec
    
    - name: Run tests chapter 01 - 03
      run: |
        continue-on-error: true
        cd ../03
        rspec

