name: Run rspec tests

on:
  push:
    branches: [ main ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        
    - name: Install rspec
      run: gem install rspec --no-document 
  
    - name: list gems
      run: gem list 

    - name: Run tests chapter 01 - 01
      if: ${{ always() }}
      run: |
        pwd
        cd chapter_01/01
        pwd
        rspec
    
    - name: Run tests chapter 01 - 03
      if: ${{ always() }}
      run: |
        pwd
        cd chapter_01/03
        rspec
    
    - name: Run tests chapter 01 - 04
      if: ${{ always() }}
      run: |
        cd ../04
        rspec
    
    - name: Run tests chapter 01 - 05
      if: ${{ always() }}
      run: |
        cd ../05
        rspec
    
    - name: Run tests chapter 01 - 06
      if: ${{ always() }}
      run: |
        cd ../06
        rspec
    
    - name: Run tests chapter 01 - 07
      if: ${{ always() }}
      run: |
        cd ../07
        rspec
    
    - name: Run tests chapter 01 - 09
      if: ${{ always() }}
      run: |
        cd ../09
        rspec

